@ApiService_HostAddress = http://localhost:5124

GET {{ApiService_HostAddress}}/weatherforecast/dev/20/5
Accept: application/json

###

GET {{ApiService_HostAddress}}/weatherforecast/data
Accept: application/json

###
