@MovieBase.Api_HostAddress = https://localhost:7267
@user=admin
@password=P@$$w0rd1
@email=admin@notadomain.com

@token=CfDJ8JHE-tf9yUBDnwjMNhyy7TuiRUFhjmSycXaotLZ6J979GlveMvzmFC9up-uJjIOB89ZAuNrnbEkgGGo7PMEYjc2XxWx46ub0vTcCnHeUK9TJz7R2QGh1UTH7rZiPdmbRcdznO6eTrDsaaGlcsHifuMsn_QY9DiU2_DK-T53juL_FIEFLJ9iMHuf9teUdfQHviWPBOqd6EZ2ZhqQBTVDjbcnkMVOiQySoiQNeSYqQsDy1tBXX7iSNuP-Uxd1nHUghgRzmcsN37bitlIL9TF-xBoW0wo3l44PQHCu6Edxxue1oiiUtOaUyAMjpKBiU7oCrfgjESzVK1hw-Qf_W0UL6R9gkkpG0LWcFOySA7GU1ORuLJqpkTt_znxC9hefveeD-2TqXw-MjZS4mwHcyPNbUv-DJpK4ymYEok0yIflCLI3bNda6XzWqbFtusZw4o_mCw1Mv8c3_ZlJyXGy2YlXGf5EZXQkcJBOr8hFbkBAjXOH_ycG3cTVLwe8VM9rWlUS6PdtjyDODnXnremo7idHQeHOIxprK20Fqbx2rY0FXBMGHSZzOZdr-gIx256YBbHBODrxlKPKV7kok8FoIn1DysAfkcx29dP4irkpGXyx0WMVPVpxi1q8QqHdQ0IwoTmSIYSfD6-WWZqxxrYWgjUndR9VsAnYVj9-QpJy2zfz87sUzWcDX5srfb1UahwV3eZ_T-eVic6Y4Su_yqNCb_JW6TfX4


POST {{MovieBase.Api_HostAddress}}/register
Content-Type: application/json

{
  "username": "{{user}}",
  "password": "{{password}}",
  "email": "{{email}}"
}

###

POST {{MovieBase.Api_HostAddress}}/login?useCookies=false
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

GET {{MovieBase.Api_HostAddress}}/movies/list/10/5
Accept: application/json

###

GET {{MovieBase.Api_HostAddress}}/movies/list
Accept: application/xml

###

GET {{MovieBase.Api_HostAddress}}/movies/1
Accept: application/json
Authorization: Bearer {{token}}

###


POST {{MovieBase.Api_HostAddress}}/movies
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "id": 0,
  "title": "Some movie",
  "director": "Nobody",
  "released": "1966-11-28"
}
###

POST {{MovieBase.Api_HostAddress}}/movies
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "Title": "Matrix 5",
  "director": "Nobody",
  "released": "1966-11-28"
}
###

DELETE {{MovieBase.Api_HostAddress}}/movies/52
Accept: application/json

###

PUT {{MovieBase.Api_HostAddress}}/movies
Content-Type: application/json

{
  "id": 53,
  "title": "Updated Name",
  "director": "Nobody",
  "released": "1966-11-28"
}
###

PATCH {{MovieBase.Api_HostAddress}}/movies/1
Accept: */*
Content-Type: application/json-patch+json

[
  {
    "op": "add",
    "path": "/director",
    "value": "Ridley Scott"
  }
]

###

